# Purpose: Dereplicate atlas SH representatives, prepare matched 16S sequences, and assign operational novelty levels.
# Panels: Figure 2E-F. BLAST commands are provided in 02_run_taxonomic_blast.sh.

library(phyloseq)
library(microbiome)
library(data.table)
library(Biostrings)
library(tidyverse)
library(vegan)
library(effectsize)
library(bigmds)
library(broom)
library(future)
library(future.apply)
library(clusterSim)
library(lme4)
library(lmerTest)
library(broom.mixed)
library(iNEXT)
library(parallel)
library(rstatix)

# Read a large OTU table and restore its first column as row names.
read_otu <- function(filepath) {
  otu <- fread(filepath, header = TRUE)
  otu <- as.data.frame(otu)
  rownames(otu) <- otu[[1]]
  otu <- otu[, -1]
  return(otu)
}

# --- Novelty of bacterial and fungal ASVs (BLAST-based) ---
# Sum total reads for each unique ASV
otu_asv0 <- read_otu("/data/wangxinyu/ITS_Public/Project/Analysis/data/ASV/otu_ASV_filterdp.csv")
otu_asv0 <- as.data.frame(t(otu_asv0))

# Extract ASV and total counts
otu_asv1 <- data.frame(ASV = row.names(otu_asv0), counts = rowSums(otu_asv0))
head(otu_asv1)


# Merge OTU table based on dereplication mapping generated by vsearch (.uc)
cluster_index0 <- read.delim("/data/wangxinyu/ITS_Public/Project/Analysis/data/ASV/refseq_filterdp_derep.uc", header = F)
cluster_index <- cluster_index0 %>%
        filter(V1 != "C") %>%
        mutate(V10 = ifelse(V10 == "*", V9, V10)) %>%
        select(V9, V10) %>%
        dplyr::rename(ASV = V9, rASV = V10)

nrow(cluster_index)
length(unique(cluster_index$rASV))

# Add index information to seqtab
otu_asv2 <- merge(cluster_index, otu_asv1, by = "ASV", all.y = TRUE)
otu_asv2 <- otu_asv2 %>% select(-ASV)

# Check
head(colnames(otu_asv2))
head(otu_asv2$rASV)

# Merge identical rASVs
setDT(otu_asv2)
otu_asv3 <- otu_asv2[, lapply(.SD, sum, na.rm = TRUE), by = rASV, .SDcols = where(is.numeric)]
otu_asv3 <- as.data.frame(otu_asv3)

# Convert sequence to row names and transpose
otu_asv3 <- otu_asv3 %>% column_to_rownames(var = "rASV")
head(otu_asv3)
nrow(otu_asv3)

path <- "/data/wangxinyu/ITS_Public/Project/Analysis/data/ASV"
write.csv(otu_asv3, file.path(path, "refseq_filterdp_derep_counts.csv"))



# --- Process the Cell 2015 dataset ---
# Count ASV reads after filtering relative abundance > 1/10,000
input_dir <- "/data/wangxinyu/ITS_Public/Project/Analysis/blast/cell2025/raw/asv_tables/"
file_list <- list.files(input_dir, pattern = "\\.txt$", full.names = TRUE)
file_list

threshold_depth <- 10000
threshold_abund <- 1 / 10000
total_counts_list <- list()
total_files <- length(file_list)

for (i in seq_along(file_list)) {
  file <- file_list[i]
  cat(sprintf("Processing file %d of %d: %s\n", i, total_files, basename(file)))

  dt <- fread(file)

  # Assume the first column is ASV ID and rename to 'ASV'
  asv_col <- names(dt)[1]
  setnames(dt, asv_col, "ASV")
  setkey(dt, ASV)

  sample_cols <- setdiff(names(dt), "ASV")

  # Remove sample columns with total reads < 10,000
  sample_totals <- colSums(dt[, ..sample_cols])
  sample_cols_to_keep <- names(sample_totals[sample_totals >= threshold_depth])
  dt <- dt[, c("ASV", sample_cols_to_keep), with = FALSE]

  if (length(sample_cols_to_keep) == 0) {
    cat("  Skipping: all samples below read threshold.\n")
    next
  }

  # For each sample, compute relative abundance and set values below threshold to 0
  for (col in sample_cols_to_keep) {
    total <- sum(dt[[col]], na.rm = TRUE)
    if (total > 0) {
      rel_abund <- dt[[col]] / total
      dt[[col]][rel_abund < threshold_abund] <- 0
    }
  }

  # Sum counts per ASV
  dt[, total_abundance := rowSums(.SD), .SDcols = sample_cols_to_keep]

  # Keep ASV and total_abundance
  total_counts_list[[i]] <- dt[, .(ASV, total_abundance)]

  # Cleanup
  rm(dt)
  gc()
}


merged_counts <- rbindlist(total_counts_list, use.names = TRUE)
final_summary <- merged_counts[, .(counts = sum(total_abundance)), by = ASV]
setorder(final_summary, -counts)
head(final_summary)
tail(final_summary)

# Remove ASVs with zero total counts
final_summary2 <- final_summary[counts > 0]
nrow(final_summary)
nrow(final_summary2)

path <- "/data/wangxinyu/ITS_Public/Project/Analysis/blast/cell2025/analysis"
write.csv(final_summary2, file.path(path, "cell2025_asv_filter_counts.csv"))


# --- Filter ASV FASTA by length and relative abundance ---
# Convert tabular ASV sequences to FASTA
df <- read.delim("/data/wangxinyu/ITS_Public/Project/Analysis/blast/cell2025/raw/obs_md.txt", header = TRUE, sep = "\t")
head(df)

seqs <- DNAStringSet(df$sequence)
names(seqs) <- df$X.OTUID
head(names(seqs))

seqs
table(width(seqs))

writeXStringSet(seqs, filepath = "/data/wangxinyu/ITS_Public/Project/Analysis/blast/cell2025/analysis/cell2025_asv_raw.fasta", format = "fasta")

# Filter by length
seqs_filter <- seqs[width(seqs) >= 100 & width(seqs) <= 600]
seqs_filter

# Keep only ASVs that pass relative abundance filtering
asv_to_keep <- read.csv("/data/wangxinyu/ITS_Public/Project/Analysis/blast/cell2025/cell2025_asv_filter_counts.csv", row.names = 1)
head(asv_to_keep)

seqs_filter2 <- seqs_filter[names(seqs_filter) %in% asv_to_keep$ASV]
seqs_filter2

writeXStringSet(seqs_filter2, filepath = "/data/wangxinyu/ITS_Public/Project/Analysis/blast/cell2025/analysis/cell2025_asv_filter2.fasta", format = "fasta")


# --- BLAST ---
# Performed by 02_run_taxonomic_blast.sh


# --- Compute novelty level of microfungal ASVs ---
refseq <- read.table("refseq_filterdp_derep_unite_final.tsv", header = T, sep = "\t", quote = "")
asv <- read.csv("otu_ASV_filterdp.csv", header = T)
asv <- asv %>% column_to_rownames(var = "X") %>% t() %>% data.frame()

ref_level <- refseq %>%
  mutate(temp = qseqid) %>%
  separate(col = temp, into = c("rASV", "size"), sep = ";size=") %>%
  mutate(level = case_when(pident >= 98.5 ~ "Species",
                           pident >= 90.0 & pident < 98.5 ~ "Genus",
                           pident >= 85.0 & pident < 90.0 ~ "Family",
                           pident >= 80.0 & pident < 85.0 ~ "Order",
                           pident >= 75.0 & pident < 80.0 ~ "Class",
                           pident >= 70.0 & pident < 75.0 ~ "Phylum",
                           T ~ "Higher_taxa_level"
  )) %>%
  mutate(level2 = case_when(pident < 90.0 ~ "Family_or_higher", T ~ level))
write.csv(ref_level, "sample_info/ref_level.csv", row.names = F)

### Novel ASVs per phylum
ref_level <- read.csv("sample_info/ref_level.csv", header = T)
ref_level1 <- ref_level %>% select(rASV, sseqid, level) %>%
  mutate(temp = sseqid) %>%
  separate(col = temp, into = c("k", "p", "c", "o", "f", "g", "s"), sep = ";")

df_sum <- table(ref_level1$p) %>% data.frame() %>% arrange(-Freq) %>% mutate(phylum = str_replace_all(Var1, "p__", ""))
level_sum <- table(ref_level1$level) %>% data.frame() %>% arrange(-Freq)

df_level <- table(ref_level1$level, ref_level1$p) %>%
  data.frame() %>%
  #mutate(number = log10(Freq + 1)) %>%
  filter(Freq > 0) %>%
  rename(Annotation_level = Var1, phylum = Var2) %>%
  mutate(phylum = str_replace_all(phylum, "p__", ""))
write.csv(df_level, "sample_info/ASV_number_annotation_level.csv", row.names = F)

### ASV annotation level
ref_level <- read.csv("sample_info/ref_level.csv", header = T)
s <- ref_level$rASV[which(ref_level$level == "Species")]
g <- ref_level$rASV[which(ref_level$level == "Genus")]
f <- ref_level$rASV[which(ref_level$level == "Family")]
o <- ref_level$rASV[which(ref_level$level == "Order")]
c <- ref_level$rASV[which(ref_level$level == "Class")]
p <- ref_level$rASV[which(ref_level$level == "Phylum")]

asv_p <- asv %>%
  filter(rownames(.) %in% p) %>%
  t() %>%
  data.frame() %>%
  mutate(sum_asv = rowSums(. >= 1)) %>%
  select(sum_asv)%>%
  rename(phylum = sum_asv)

asv_c <- asv %>%
  filter(rownames(.) %in% c) %>%
  t() %>%
  data.frame() %>%
  mutate(sum_asv = rowSums(. >= 1)) %>%
  select(sum_asv)%>%
  rename(class = sum_asv)

asv_o <- asv %>%
  filter(rownames(.) %in% o) %>%
  t() %>%
  data.frame() %>%
  mutate(sum_asv = rowSums(. >= 1)) %>%
  select(sum_asv)%>%
  rename(order = sum_asv)

asv_f <- asv %>%
  filter(rownames(.) %in% f) %>%
  t() %>%
  data.frame() %>%
  mutate(sum_asv = rowSums(. >= 1)) %>%
  select(sum_asv)%>%
  rename(family = sum_asv)


asv_g <- asv %>%
  filter(rownames(.) %in% g) %>%
  t() %>%
  data.frame() %>%
  mutate(sum_asv = rowSums(. >= 1)) %>%
  select(sum_asv)%>%
  rename(genus = sum_asv)

asv_s <- asv %>%
  filter(rownames(.) %in% s) %>%
  t() %>%
  data.frame() %>%
  mutate(sum_asv = rowSums(. >= 1)) %>%
  select(sum_asv)%>%
  rename(species = sum_asv)

asv_summary <- data.frame(
  ID = rownames(asv_s),
  species = asv_s$species,
  genus = asv_g$genus,
  family = asv_f$family,
  order = asv_o$order,
  class = asv_c$class,
  phylum = asv_p$phylum
  ) %>%
  mutate(ASV_detect = species + genus + family + order + class + phylum) %>%
  mutate(novel_asv = ASV_detect - species) %>%
  mutate(novel_asv_ratio = novel_asv / ASV_detect) %>%
  left_join(metadata, by = "ID") %>%
  filter(!is.na(Continent))
write.csv(asv_summary, "sample_info/asv_summary.csv")

asv_summary <- read.csv("sample_info/asv_summary.csv", row.names = 1)
asv_ratio <- asv_summary %>%
  mutate(Novel = genus + family + order + class + phylum, `Known species` = species) %>%
  #pivot_longer(cols = c("species", "genus", "family", "order", "class", "phylum"), names_to = "levels", values_to = "number") %>%
  pivot_longer(cols = c("Known species", "Novel"), names_to = "levels2", values_to = "number") %>%
  mutate(ratio = number/ASV_detect) %>%
  #mutate(levels2 = case_when(levels %in% c("species", "genus") ~ levels, T ~ "family_or_higher")) %>%
  filter(!Country == "missing") %>%
  group_by(levels2, Continent) %>%
  summarise(Ratio_mean = mean(ratio, na.rm = TRUE), .groups = "drop") %>%
  ungroup()
write.csv(asv_ratio, "sample_info/asv_ratio.csv", row.names = F)
